### ISSUE TITLE
there is no map

### ISSUE THREAD

**Issue by ahmedmuhammedpro** [tinhpv/indoor-navigation-system-qrcode-augmented-reality#1]
when running the there is no map shown at all even for searching with samples terms.
 
![Screenshot_1652882883](https://user-images.githubusercontent.com/59180483/169061956-190e431f-9360-4305-9434-a0c8e7afa22e.png)

**Comment by tinhpv** [comment]
Hi @ahmedmuhammedpro
It's been a long time since we built this project, which was built for learning purpose only.
all data was loaded from server but it was dead. 
Thanks for your interest!
